version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes: 
        - .:/olympics/src/app
        - /olympics/src/app/node_module
    command: npm run start:debug
    env_file: 
        - .env
    depends_on: 
        - postgres
    environment: 
        DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
        NODE_ENV: development
        PORT: 3000
    ports:
        - 8080:3000
        - 9229:9229

  postgres:
      container_name: postgres
      image: postgres:10
      environment: 
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_DB: ${POSTGRES_DB}
          PG_DATA: /var/lib/postgresql/data
      ports:
          - 35000:5432